# Generated by Django 5.1.4 on 2026-07-02 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=100, help_text='Kleiner = zuerst geprüft')),
                ('enabled', models.BooleanField(default=True)),
                ('match', models.JSONField(blank=True, default=dict)),
                ('then', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Klassifizierungsregel',
                'verbose_name_plural': 'Klassifizierungsregeln',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Correspondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Korrespondent',
                'verbose_name_plural': 'Korrespondenten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Zahl'), ('date', 'Datum'), ('currency', 'Währung'), ('boolean', 'Ja/Nein')], max_length=16)),
            ],
            options={
                'verbose_name': 'Zusatzfeld',
                'verbose_name_plural': 'Zusatzfelder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Dokumenttyp',
                'verbose_name_plural': 'Dokumenttypen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoragePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('path_template', models.CharField(default='archive/{jahr}/{korrespondent}/{titel}', max_length=512)),
            ],
            options={
                'verbose_name': 'Ablagepfad',
                'verbose_name_plural': 'Ablagepfade',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(help_text='z. B. create, update, delete', max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit-Eintrag',
                'verbose_name_plural': 'Audit-Log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(blank=True, help_text='Datum des Dokuments selbst (z. B. Rechnungsdatum)', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Aufnahme ins DMS')),
                ('correspondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.correspondent')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttype')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('file_path', models.CharField(help_text='Original auf der Platte', max_length=1024)),
                ('archive_path', models.CharField(blank=True, help_text="OCR'tes PDF/A", max_length=1024)),
                ('sha256', models.CharField(help_text='Integritäts-Hash der Datei', max_length=64)),
                ('prev_hash', models.CharField(blank=True, help_text='sha256 der Vorgängerversion – bildet die Hash-Kette', max_length=64)),
                ('ocr_text', models.TextField(blank=True, help_text='Volltext (später FTS-indiziert)')),
                ('mime_type', models.CharField(blank=True, max_length=127)),
                ('size', models.BigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_immutable', models.BooleanField(default=False, help_text='WORM-Flag – wird in Stufe 4 (Revisionssicherheit) erzwungen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Dokumentversion',
                'verbose_name_plural': 'Dokumentversionen',
                'ordering': ['document', 'version_no'],
                'unique_together': {('document', 'version_no')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion'),
        ),
        migrations.AddField(
            model_name='document',
            name='storage_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.storagepath'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex-Farbe', max_length=7)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='documents.tag')),
            ],
            options={
                'verbose_name': 'Schlagwort',
                'verbose_name_plural': 'Schlagworte',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.tag'),
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.customfield')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='documents.document')),
            ],
            options={
                'verbose_name': 'Zusatzfeld-Wert',
                'verbose_name_plural': 'Zusatzfeld-Werte',
                'unique_together': {('document', 'field')},
            },
        ),
    ]
