# Generated by Django 5.1.4 on 2026-07-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='thumbnail_path',
            field=models.CharField(blank=True, help_text='Miniaturbild der ersten Seite (JPEG)', max_length=1024),
        ),
    ]
