# Generated by Django 5.1.4 on 2026-07-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentversion_thumbnail_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_suggested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
