# Generated by Django 5.1.4 on 2026-07-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_ai_suggested_at_document_ai_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='classification',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
