# Generated by Django 5.1.4 on 2026-07-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_mailaccount_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('entwurf', 'Entwurf'), ('zur_freigabe', 'Zur Freigabe'), ('freigegeben', 'Freigegeben'), ('abgelehnt', 'Abgelehnt')], default='entwurf', max_length=16),
        ),
    ]
