# Generated by Django 5.1.4 on 2026-07-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_mailaccount_password_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="ocr_duration_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="ocr_engine",
            field=models.CharField(default="ocrmypdf", max_length=30),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="ocr_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="ocr_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="ocr_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="ocr_text",
            field=models.TextField(blank=True),
        ),
    ]
